export default[
  {
    login: 'marvin',
    id: 557,
    node_id: 'MDQ6VXNlcjU1Nw==',
    avatar_url: 'https://avatars.githubusercontent.com/u/557?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/marvin',
    html_url: 'https://github.com/marvin',
    followers_url: 'https://api.github.com/users/marvin/followers',
    following_url: 'https://api.github.com/users/marvin/following{/other_user}',
    gists_url: 'https://api.github.com/users/marvin/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/marvin/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/marvin/subscriptions',
    organizations_url: 'https://api.github.com/users/marvin/orgs',
    repos_url: 'https://api.github.com/users/marvin/repos',
    events_url: 'https://api.github.com/users/marvin/events{/privacy}',
    received_events_url: 'https://api.github.com/users/marvin/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'kirooshu',
    id: 577,
    node_id: 'MDQ6VXNlcjU3Nw==',
    avatar_url: 'https://avatars.githubusercontent.com/u/577?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/kirooshu',
    html_url: 'https://github.com/kirooshu',
    followers_url: 'https://api.github.com/users/kirooshu/followers',
    following_url:
      'https://api.github.com/users/kirooshu/following{/other_user}',
    gists_url: 'https://api.github.com/users/kirooshu/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/kirooshu/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/kirooshu/subscriptions',
    organizations_url: 'https://api.github.com/users/kirooshu/orgs',
    repos_url: 'https://api.github.com/users/kirooshu/repos',
    events_url: 'https://api.github.com/users/kirooshu/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/kirooshu/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Sija',
    id: 988,
    node_id: 'MDQ6VXNlcjk4OA==',
    avatar_url: 'https://avatars.githubusercontent.com/u/988?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Sija',
    html_url: 'https://github.com/Sija',
    followers_url: 'https://api.github.com/users/Sija/followers',
    following_url: 'https://api.github.com/users/Sija/following{/other_user}',
    gists_url: 'https://api.github.com/users/Sija/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/Sija/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Sija/subscriptions',
    organizations_url: 'https://api.github.com/users/Sija/orgs',
    repos_url: 'https://api.github.com/users/Sija/repos',
    events_url: 'https://api.github.com/users/Sija/events{/privacy}',
    received_events_url: 'https://api.github.com/users/Sija/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'andrew',
    id: 1060,
    node_id: 'MDQ6VXNlcjEwNjA=',
    avatar_url: 'https://avatars.githubusercontent.com/u/1060?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/andrew',
    html_url: 'https://github.com/andrew',
    followers_url: 'https://api.github.com/users/andrew/followers',
    following_url: 'https://api.github.com/users/andrew/following{/other_user}',
    gists_url: 'https://api.github.com/users/andrew/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/andrew/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/andrew/subscriptions',
    organizations_url: 'https://api.github.com/users/andrew/orgs',
    repos_url: 'https://api.github.com/users/andrew/repos',
    events_url: 'https://api.github.com/users/andrew/events{/privacy}',
    received_events_url: 'https://api.github.com/users/andrew/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'gruner',
    id: 2345,
    node_id: 'MDQ6VXNlcjIzNDU=',
    avatar_url: 'https://avatars.githubusercontent.com/u/2345?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/gruner',
    html_url: 'https://github.com/gruner',
    followers_url: 'https://api.github.com/users/gruner/followers',
    following_url: 'https://api.github.com/users/gruner/following{/other_user}',
    gists_url: 'https://api.github.com/users/gruner/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/gruner/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/gruner/subscriptions',
    organizations_url: 'https://api.github.com/users/gruner/orgs',
    repos_url: 'https://api.github.com/users/gruner/repos',
    events_url: 'https://api.github.com/users/gruner/events{/privacy}',
    received_events_url: 'https://api.github.com/users/gruner/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'pfefferle',
    id: 2373,
    node_id: 'MDQ6VXNlcjIzNzM=',
    avatar_url: 'https://avatars.githubusercontent.com/u/2373?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/pfefferle',
    html_url: 'https://github.com/pfefferle',
    followers_url: 'https://api.github.com/users/pfefferle/followers',
    following_url:
      'https://api.github.com/users/pfefferle/following{/other_user}',
    gists_url: 'https://api.github.com/users/pfefferle/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/pfefferle/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/pfefferle/subscriptions',
    organizations_url: 'https://api.github.com/users/pfefferle/orgs',
    repos_url: 'https://api.github.com/users/pfefferle/repos',
    events_url: 'https://api.github.com/users/pfefferle/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/pfefferle/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Aeon',
    id: 2532,
    node_id: 'MDQ6VXNlcjI1MzI=',
    avatar_url: 'https://avatars.githubusercontent.com/u/2532?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Aeon',
    html_url: 'https://github.com/Aeon',
    followers_url: 'https://api.github.com/users/Aeon/followers',
    following_url: 'https://api.github.com/users/Aeon/following{/other_user}',
    gists_url: 'https://api.github.com/users/Aeon/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/Aeon/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Aeon/subscriptions',
    organizations_url: 'https://api.github.com/users/Aeon/orgs',
    repos_url: 'https://api.github.com/users/Aeon/repos',
    events_url: 'https://api.github.com/users/Aeon/events{/privacy}',
    received_events_url: 'https://api.github.com/users/Aeon/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'poulikov',
    id: 2836,
    node_id: 'MDQ6VXNlcjI4MzY=',
    avatar_url: 'https://avatars.githubusercontent.com/u/2836?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/poulikov',
    html_url: 'https://github.com/poulikov',
    followers_url: 'https://api.github.com/users/poulikov/followers',
    following_url:
      'https://api.github.com/users/poulikov/following{/other_user}',
    gists_url: 'https://api.github.com/users/poulikov/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/poulikov/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/poulikov/subscriptions',
    organizations_url: 'https://api.github.com/users/poulikov/orgs',
    repos_url: 'https://api.github.com/users/poulikov/repos',
    events_url: 'https://api.github.com/users/poulikov/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/poulikov/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'nikolay',
    id: 2882,
    node_id: 'MDQ6VXNlcjI4ODI=',
    avatar_url: 'https://avatars.githubusercontent.com/u/2882?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/nikolay',
    html_url: 'https://github.com/nikolay',
    followers_url: 'https://api.github.com/users/nikolay/followers',
    following_url:
      'https://api.github.com/users/nikolay/following{/other_user}',
    gists_url: 'https://api.github.com/users/nikolay/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/nikolay/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/nikolay/subscriptions',
    organizations_url: 'https://api.github.com/users/nikolay/orgs',
    repos_url: 'https://api.github.com/users/nikolay/repos',
    events_url: 'https://api.github.com/users/nikolay/events{/privacy}',
    received_events_url: 'https://api.github.com/users/nikolay/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'stinie',
    id: 3000,
    node_id: 'MDQ6VXNlcjMwMDA=',
    avatar_url: 'https://avatars.githubusercontent.com/u/3000?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/stinie',
    html_url: 'https://github.com/stinie',
    followers_url: 'https://api.github.com/users/stinie/followers',
    following_url: 'https://api.github.com/users/stinie/following{/other_user}',
    gists_url: 'https://api.github.com/users/stinie/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/stinie/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/stinie/subscriptions',
    organizations_url: 'https://api.github.com/users/stinie/orgs',
    repos_url: 'https://api.github.com/users/stinie/repos',
    events_url: 'https://api.github.com/users/stinie/events{/privacy}',
    received_events_url: 'https://api.github.com/users/stinie/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'mdiedric',
    id: 3003,
    node_id: 'MDQ6VXNlcjMwMDM=',
    avatar_url: 'https://avatars.githubusercontent.com/u/3003?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/mdiedric',
    html_url: 'https://github.com/mdiedric',
    followers_url: 'https://api.github.com/users/mdiedric/followers',
    following_url:
      'https://api.github.com/users/mdiedric/following{/other_user}',
    gists_url: 'https://api.github.com/users/mdiedric/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/mdiedric/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/mdiedric/subscriptions',
    organizations_url: 'https://api.github.com/users/mdiedric/orgs',
    repos_url: 'https://api.github.com/users/mdiedric/repos',
    events_url: 'https://api.github.com/users/mdiedric/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/mdiedric/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'tpaksu',
    id: 3295,
    node_id: 'MDQ6VXNlcjMyOTU=',
    avatar_url: 'https://avatars.githubusercontent.com/u/3295?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/tpaksu',
    html_url: 'https://github.com/tpaksu',
    followers_url: 'https://api.github.com/users/tpaksu/followers',
    following_url: 'https://api.github.com/users/tpaksu/following{/other_user}',
    gists_url: 'https://api.github.com/users/tpaksu/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/tpaksu/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/tpaksu/subscriptions',
    organizations_url: 'https://api.github.com/users/tpaksu/orgs',
    repos_url: 'https://api.github.com/users/tpaksu/repos',
    events_url: 'https://api.github.com/users/tpaksu/events{/privacy}',
    received_events_url: 'https://api.github.com/users/tpaksu/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'makyox',
    id: 3603,
    node_id: 'MDQ6VXNlcjM2MDM=',
    avatar_url: 'https://avatars.githubusercontent.com/u/3603?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/makyox',
    html_url: 'https://github.com/makyox',
    followers_url: 'https://api.github.com/users/makyox/followers',
    following_url: 'https://api.github.com/users/makyox/following{/other_user}',
    gists_url: 'https://api.github.com/users/makyox/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/makyox/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/makyox/subscriptions',
    organizations_url: 'https://api.github.com/users/makyox/orgs',
    repos_url: 'https://api.github.com/users/makyox/repos',
    events_url: 'https://api.github.com/users/makyox/events{/privacy}',
    received_events_url: 'https://api.github.com/users/makyox/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'darron',
    id: 5176,
    node_id: 'MDQ6VXNlcjUxNzY=',
    avatar_url: 'https://avatars.githubusercontent.com/u/5176?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/darron',
    html_url: 'https://github.com/darron',
    followers_url: 'https://api.github.com/users/darron/followers',
    following_url: 'https://api.github.com/users/darron/following{/other_user}',
    gists_url: 'https://api.github.com/users/darron/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/darron/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/darron/subscriptions',
    organizations_url: 'https://api.github.com/users/darron/orgs',
    repos_url: 'https://api.github.com/users/darron/repos',
    events_url: 'https://api.github.com/users/darron/events{/privacy}',
    received_events_url: 'https://api.github.com/users/darron/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'brucep',
    id: 5489,
    node_id: 'MDQ6VXNlcjU0ODk=',
    avatar_url: 'https://avatars.githubusercontent.com/u/5489?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/brucep',
    html_url: 'https://github.com/brucep',
    followers_url: 'https://api.github.com/users/brucep/followers',
    following_url: 'https://api.github.com/users/brucep/following{/other_user}',
    gists_url: 'https://api.github.com/users/brucep/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/brucep/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/brucep/subscriptions',
    organizations_url: 'https://api.github.com/users/brucep/orgs',
    repos_url: 'https://api.github.com/users/brucep/repos',
    events_url: 'https://api.github.com/users/brucep/events{/privacy}',
    received_events_url: 'https://api.github.com/users/brucep/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'vincent',
    id: 5623,
    node_id: 'MDQ6VXNlcjU2MjM=',
    avatar_url: 'https://avatars.githubusercontent.com/u/5623?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/vincent',
    html_url: 'https://github.com/vincent',
    followers_url: 'https://api.github.com/users/vincent/followers',
    following_url:
      'https://api.github.com/users/vincent/following{/other_user}',
    gists_url: 'https://api.github.com/users/vincent/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/vincent/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/vincent/subscriptions',
    organizations_url: 'https://api.github.com/users/vincent/orgs',
    repos_url: 'https://api.github.com/users/vincent/repos',
    events_url: 'https://api.github.com/users/vincent/events{/privacy}',
    received_events_url: 'https://api.github.com/users/vincent/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'fain182',
    id: 5879,
    node_id: 'MDQ6VXNlcjU4Nzk=',
    avatar_url: 'https://avatars.githubusercontent.com/u/5879?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/fain182',
    html_url: 'https://github.com/fain182',
    followers_url: 'https://api.github.com/users/fain182/followers',
    following_url:
      'https://api.github.com/users/fain182/following{/other_user}',
    gists_url: 'https://api.github.com/users/fain182/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/fain182/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/fain182/subscriptions',
    organizations_url: 'https://api.github.com/users/fain182/orgs',
    repos_url: 'https://api.github.com/users/fain182/repos',
    events_url: 'https://api.github.com/users/fain182/events{/privacy}',
    received_events_url: 'https://api.github.com/users/fain182/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'ianvanness',
    id: 6192,
    node_id: 'MDQ6VXNlcjYxOTI=',
    avatar_url: 'https://avatars.githubusercontent.com/u/6192?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/ianvanness',
    html_url: 'https://github.com/ianvanness',
    followers_url: 'https://api.github.com/users/ianvanness/followers',
    following_url:
      'https://api.github.com/users/ianvanness/following{/other_user}',
    gists_url: 'https://api.github.com/users/ianvanness/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/ianvanness/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/ianvanness/subscriptions',
    organizations_url: 'https://api.github.com/users/ianvanness/orgs',
    repos_url: 'https://api.github.com/users/ianvanness/repos',
    events_url: 'https://api.github.com/users/ianvanness/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/ianvanness/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'openweb',
    id: 6490,
    node_id: 'MDQ6VXNlcjY0OTA=',
    avatar_url: 'https://avatars.githubusercontent.com/u/6490?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/openweb',
    html_url: 'https://github.com/openweb',
    followers_url: 'https://api.github.com/users/openweb/followers',
    following_url:
      'https://api.github.com/users/openweb/following{/other_user}',
    gists_url: 'https://api.github.com/users/openweb/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/openweb/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/openweb/subscriptions',
    organizations_url: 'https://api.github.com/users/openweb/orgs',
    repos_url: 'https://api.github.com/users/openweb/repos',
    events_url: 'https://api.github.com/users/openweb/events{/privacy}',
    received_events_url: 'https://api.github.com/users/openweb/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'bangpound',
    id: 6731,
    node_id: 'MDQ6VXNlcjY3MzE=',
    avatar_url: 'https://avatars.githubusercontent.com/u/6731?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/bangpound',
    html_url: 'https://github.com/bangpound',
    followers_url: 'https://api.github.com/users/bangpound/followers',
    following_url:
      'https://api.github.com/users/bangpound/following{/other_user}',
    gists_url: 'https://api.github.com/users/bangpound/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/bangpound/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/bangpound/subscriptions',
    organizations_url: 'https://api.github.com/users/bangpound/orgs',
    repos_url: 'https://api.github.com/users/bangpound/repos',
    events_url: 'https://api.github.com/users/bangpound/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/bangpound/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'jchatard',
    id: 6790,
    node_id: 'MDQ6VXNlcjY3OTA=',
    avatar_url: 'https://avatars.githubusercontent.com/u/6790?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/jchatard',
    html_url: 'https://github.com/jchatard',
    followers_url: 'https://api.github.com/users/jchatard/followers',
    following_url:
      'https://api.github.com/users/jchatard/following{/other_user}',
    gists_url: 'https://api.github.com/users/jchatard/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/jchatard/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/jchatard/subscriptions',
    organizations_url: 'https://api.github.com/users/jchatard/orgs',
    repos_url: 'https://api.github.com/users/jchatard/repos',
    events_url: 'https://api.github.com/users/jchatard/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/jchatard/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'erinther',
    id: 6953,
    node_id: 'MDQ6VXNlcjY5NTM=',
    avatar_url: 'https://avatars.githubusercontent.com/u/6953?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/erinther',
    html_url: 'https://github.com/erinther',
    followers_url: 'https://api.github.com/users/erinther/followers',
    following_url:
      'https://api.github.com/users/erinther/following{/other_user}',
    gists_url: 'https://api.github.com/users/erinther/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/erinther/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/erinther/subscriptions',
    organizations_url: 'https://api.github.com/users/erinther/orgs',
    repos_url: 'https://api.github.com/users/erinther/repos',
    events_url: 'https://api.github.com/users/erinther/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/erinther/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'mateusza',
    id: 7002,
    node_id: 'MDQ6VXNlcjcwMDI=',
    avatar_url: 'https://avatars.githubusercontent.com/u/7002?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/mateusza',
    html_url: 'https://github.com/mateusza',
    followers_url: 'https://api.github.com/users/mateusza/followers',
    following_url:
      'https://api.github.com/users/mateusza/following{/other_user}',
    gists_url: 'https://api.github.com/users/mateusza/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/mateusza/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/mateusza/subscriptions',
    organizations_url: 'https://api.github.com/users/mateusza/orgs',
    repos_url: 'https://api.github.com/users/mateusza/repos',
    events_url: 'https://api.github.com/users/mateusza/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/mateusza/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'alfredwesterveld',
    id: 7066,
    node_id: 'MDQ6VXNlcjcwNjY=',
    avatar_url: 'https://avatars.githubusercontent.com/u/7066?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/alfredwesterveld',
    html_url: 'https://github.com/alfredwesterveld',
    followers_url: 'https://api.github.com/users/alfredwesterveld/followers',
    following_url:
      'https://api.github.com/users/alfredwesterveld/following{/other_user}',
    gists_url: 'https://api.github.com/users/alfredwesterveld/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/alfredwesterveld/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/alfredwesterveld/subscriptions',
    organizations_url: 'https://api.github.com/users/alfredwesterveld/orgs',
    repos_url: 'https://api.github.com/users/alfredwesterveld/repos',
    events_url:
      'https://api.github.com/users/alfredwesterveld/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/alfredwesterveld/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'paolomainardi',
    id: 8747,
    node_id: 'MDQ6VXNlcjg3NDc=',
    avatar_url: 'https://avatars.githubusercontent.com/u/8747?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/paolomainardi',
    html_url: 'https://github.com/paolomainardi',
    followers_url: 'https://api.github.com/users/paolomainardi/followers',
    following_url:
      'https://api.github.com/users/paolomainardi/following{/other_user}',
    gists_url: 'https://api.github.com/users/paolomainardi/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/paolomainardi/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/paolomainardi/subscriptions',
    organizations_url: 'https://api.github.com/users/paolomainardi/orgs',
    repos_url: 'https://api.github.com/users/paolomainardi/repos',
    events_url: 'https://api.github.com/users/paolomainardi/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/paolomainardi/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'cjoh',
    id: 8958,
    node_id: 'MDQ6VXNlcjg5NTg=',
    avatar_url: 'https://avatars.githubusercontent.com/u/8958?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/cjoh',
    html_url: 'https://github.com/cjoh',
    followers_url: 'https://api.github.com/users/cjoh/followers',
    following_url: 'https://api.github.com/users/cjoh/following{/other_user}',
    gists_url: 'https://api.github.com/users/cjoh/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/cjoh/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/cjoh/subscriptions',
    organizations_url: 'https://api.github.com/users/cjoh/orgs',
    repos_url: 'https://api.github.com/users/cjoh/repos',
    events_url: 'https://api.github.com/users/cjoh/events{/privacy}',
    received_events_url: 'https://api.github.com/users/cjoh/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'mcabreradev',
    id: 9103,
    node_id: 'MDQ6VXNlcjkxMDM=',
    avatar_url: 'https://avatars.githubusercontent.com/u/9103?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/mcabreradev',
    html_url: 'https://github.com/mcabreradev',
    followers_url: 'https://api.github.com/users/mcabreradev/followers',
    following_url:
      'https://api.github.com/users/mcabreradev/following{/other_user}',
    gists_url: 'https://api.github.com/users/mcabreradev/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/mcabreradev/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/mcabreradev/subscriptions',
    organizations_url: 'https://api.github.com/users/mcabreradev/orgs',
    repos_url: 'https://api.github.com/users/mcabreradev/repos',
    events_url: 'https://api.github.com/users/mcabreradev/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/mcabreradev/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'co3k',
    id: 9206,
    node_id: 'MDQ6VXNlcjkyMDY=',
    avatar_url: 'https://avatars.githubusercontent.com/u/9206?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/co3k',
    html_url: 'https://github.com/co3k',
    followers_url: 'https://api.github.com/users/co3k/followers',
    following_url: 'https://api.github.com/users/co3k/following{/other_user}',
    gists_url: 'https://api.github.com/users/co3k/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/co3k/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/co3k/subscriptions',
    organizations_url: 'https://api.github.com/users/co3k/orgs',
    repos_url: 'https://api.github.com/users/co3k/repos',
    events_url: 'https://api.github.com/users/co3k/events{/privacy}',
    received_events_url: 'https://api.github.com/users/co3k/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'davidwinter',
    id: 9681,
    node_id: 'MDQ6VXNlcjk2ODE=',
    avatar_url: 'https://avatars.githubusercontent.com/u/9681?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/davidwinter',
    html_url: 'https://github.com/davidwinter',
    followers_url: 'https://api.github.com/users/davidwinter/followers',
    following_url:
      'https://api.github.com/users/davidwinter/following{/other_user}',
    gists_url: 'https://api.github.com/users/davidwinter/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/davidwinter/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/davidwinter/subscriptions',
    organizations_url: 'https://api.github.com/users/davidwinter/orgs',
    repos_url: 'https://api.github.com/users/davidwinter/repos',
    events_url: 'https://api.github.com/users/davidwinter/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/davidwinter/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'elliot',
    id: 9938,
    node_id: 'MDQ6VXNlcjk5Mzg=',
    avatar_url: 'https://avatars.githubusercontent.com/u/9938?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/elliot',
    html_url: 'https://github.com/elliot',
    followers_url: 'https://api.github.com/users/elliot/followers',
    following_url: 'https://api.github.com/users/elliot/following{/other_user}',
    gists_url: 'https://api.github.com/users/elliot/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/elliot/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/elliot/subscriptions',
    organizations_url: 'https://api.github.com/users/elliot/orgs',
    repos_url: 'https://api.github.com/users/elliot/repos',
    events_url: 'https://api.github.com/users/elliot/events{/privacy}',
    received_events_url: 'https://api.github.com/users/elliot/received_events',
    type: 'User',
    site_admin: false,
  },
]
